### ISSUE TITLE
dom not ready / no preview - Older Obsidian versions supported?

### ISSUE THREAD

**Issue by syd-h** [l1xnan/obsidian-better-export-pdf#278]
Another but different 'dom not ready' error. Unlike the previous one this does not seem to be a conflict with obsidian-metatable #229 . I also have no preview window if this is related.

One thing to note is that I am not running the newest version of Obsidian v1.xx but v.0.15.9 before they did their own version of the Sliding Panes/vertical tabs. I have tried with only this plugin active but the error remained consistent. 

Is this simply an error due to older version incompatibility?

![image](https://github.com/user-attachments/assets/276b6860-60e0-4ed0-b517-bf783dc6cb76)
![image](https://github.com/user-attachments/assets/23394b8a-c979-4992-bdbc-b92ff7815ffe)

```
plugin:better-export-pdf:20381 Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at renderMarkdown (plugin:better-export-pdf:20381:9)
    at ExportConfigModal.renderFiles (plugin:better-export-pdf:20542:26)
    at ExportConfigModal.appendWebview (plugin:better-export-pdf:20627:18)
    at eval (plugin:better-export-pdf:20690:18)
    at window.createEl (enhance.js:1:8266)
    at HTMLDivElement.Node.createEl (enhance.js:1:7398)
    at HTMLDivElement.Node.createDiv (enhance.js:1:7466)
    at ExportConfigModal.onOpen (plugin:better-export-pdf:20684:31)
    at ExportConfigModal.e.open (app.js:1:1128457)
renderMarkdown @ plugin:better-export-pdf:20381
renderFiles @ plugin:better-export-pdf:20542
appendWebview @ plugin:better-export-pdf:20627
eval @ plugin:better-export-pdf:20690
window.createEl @ enhance.js:1
Node.createEl @ enhance.js:1
Node.createDiv @ enhance.js:1
onOpen @ plugin:better-export-pdf:20684
e.open @ app.js:1
checkCallback @ plugin:better-export-pdf:21060
yH @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
await in e.onKeyEvent (async)
window.createEl @ enhance.js:1
Node.createEl @ enhance.js:1
Node.createDiv @ enhance.js:1
onOpen @ plugin:better-export-pdf:20684
e.open @ app.js:1
checkCallback @ plugin:better-export-pdf:21060
yH @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
```

**Comment by l1xnan** [comment]
It may be that the Electron kernel of the old version of obsidian does not support some new js features, it is recommended to upgrade to the latest obsidian.

**Comment by syd-h** [comment]
Eventually but the current work flow is better suited to v.0.15.9 currently setup. This is just the first addon issue I've come across like that since they did the big version update.

**Comment by l1xnan** [comment]
> Eventually but the current work flow is better suited to my v.0.15.9 currently setup. This is just the first addon issue I've come across like that since they did the big version update.

![image](https://github.com/user-attachments/assets/622d65d8-ba45-42f0-bcf0-f28b777ec2b7)
Is it possible to click on the error link to see exactly which line of code is reporting the error so I can make a targeted fix?

**Comment by syd-h** [comment]
Line 20381 is as follows.
`  Array.from(fragment.children).forEach((item) => {`

![image](https://github.com/user-attachments/assets/c88c027e-b1c7-4cba-9b59-355bb62a3aaa)

Here are also the other lines for the errors in the better-export-pdf plugin if that helps any.

    at ExportConfigModal.renderFiles (plugin:better-export-pdf:20542:26)

`      const doc0 = await renderMarkdown(app, this.file, this.config);`

![image](https://github.com/user-attachments/assets/039454d1-ca28-418c-9dbb-d2a9ec44e80d)

    at ExportConfigModal.appendWebview (plugin:better-export-pdf:20627:18)

`      await this.renderFiles();`

![image](https://github.com/user-attachments/assets/46caebf0-e8a5-49ff-8f17-ea992398a8b8)

    at eval (plugin:better-export-pdf:20690:18)

`      await this.appendWebview(el);`

![image](https://github.com/user-attachments/assets/e0b8e739-33ba-4e5a-8bc9-30dc278355e4)

    at ExportConfigModal.onOpen (plugin:better-export-pdf:20684:31)

`    this.previewDiv = wrapper.createDiv({ attr: { style: "flex:auto; position:relative;" } }, async (el) => {`

![image](https://github.com/user-attachments/assets/29321741-c775-41ff-a054-519a7e24fb10)
