### ISSUE TITLE
Export failed.

### ISSUE THREAD

**Issue by Latisha19** [l1xnan/obsidian-better-export-pdf#366]
Hello,

I'm using version 1.9.2. 

In the past, I could export normally when using this plug-in, but a problem suddenly occurred today. (The last export was on 12/20)

I tried many times today but failed to export successfully.

I also found out that there is the latest version 1.10.0, but it still failed.

After upgrading, I turned on the debug mode and found that the console reported "Uncaught ReferenceError: electron is not defined. at HTMLDocument.<anonymous> (help.js:1:306796)".

What do you think I should do next?

Thanks for any advice.

**Comment by l1xnan** [comment]
The debug mode is designed to check whether there are any abnormalities in rendering. If the export fails, press `Ctrl + Shift + I` to open the developer console and check if there are any abnormal errors.

**Comment by its-truce** [comment]
I seem to be getting the following error:

```
Uncaught (in promise) Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at WebViewElement.getWebContentsId (node:electron/js2c/renderer_init:2:23741)
    at e.<computed> [as executeJavaScript] (node:electron/js2c/renderer_init:2:27962)
    at eval (plugin:better-export-pdf:20653:39)
    at Array.forEach (<anonymous>)
    at ExportConfigModal.calcWebviewSize (plugin:better-export-pdf:20651:19)
    at async ExportConfigModal.appendWebviews (plugin:better-export-pdf:20745:5)
    at async eval (plugin:better-export-pdf:20760:7)
```

Tried reinstalling twice. I click Export, choose the location and click OK. Nothing happens.

**Comment by Ethan-Crisp** [comment]
您好，报错信息如下：
Uncaught (in promise) ReferenceError: electron is not defined
    at help.js:1:306796
    at enhance.js:1:13190
    at help.js:1:299943
    at help.js:1:1732
    at Object.next (help.js:1:1837)
    at l (help.js:1:555)
---
遇到同样问题，无法导出，点击导出选择路径之后，没有新文件生成。
在官方安装插件之后，已经试过下载最新解压包，并将文件全部移动到plugin目录下，bug依旧存在。
请注意，官方下载的插件只包含几个文件，main，data之类的。而解压包里则包含了很多文件，数量明显不一致。

**Comment by l1xnan** [comment]
@its-truce @Ethan-Crisp Is this problem for every file or only some files? Can you provide the problem note file?

**Comment by Latisha19** [comment]
Today I tried using `Ctrl + Shift + I` to open console, no error, and it exported successfully. Not know why.
And debug mode's console still got the same error.
I don’t understand the beginning and end of the reason at all.
Sorry for nothing can support.

**Comment by Ethan-Crisp** [comment]
您好，已经测试过不同类型的md笔记文件，包括：纯文本，文本+引用，文本+图片+引用，均无法导出。
3次导出报了一样的bug：
plugin:better-export-pdf:20221 Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Invalid print parameters: scale is outside of [0.1 - 2] range
    at IpcRendererInternal.invoke (node:electron/js2c/renderer_init:2:11410)
    at async exportToPDF (plugin:better-export-pdf:20209:16)
    at async handleExport (plugin:better-export-pdf:20793:11)

没有调整参数，按照默认的宽高页边距等进行导出。

**Comment by its-truce** [comment]
> @its-truce @Ethan-Crisp Is this problem for every file or only some files? Can you provide the problem note file?

Sorry for the late reply, but it seems to be the case for every note.

**Comment by Ethan-Crisp** [comment]
https://forum-zh.obsidian.md/t/topic/42854/5
安装完插件不仅better export PDF本身无法导出，会导致原生obsidian的导出功能也不生效。
目前已经将插件完全删除，之后原生导出功能已经回复正常。
---
After the plug-in is installed, not only the better export PDF itself cannot be exported, but also the native obsidian export function does not take effect. Now the plug-in has been completely deleted, and the native export function has returned to normal

**Comment by l1xnan** [comment]
@Ethan-Crisp @its-truce @Latisha19 In fact, I've never been able to reproduce these issues.  I don't know what changes the new version of Obsidian has made, but it has indeed affected the plugin.  I made some modifications to the areas where I suspected problems might occur and released a new version.  If possible, could you guys help test it?  It would be best to back up and delete the plugin's `data.json` file before retesting. Thank you very much.

**Comment by Seb-stian** [comment]
@l1xnan I've tried your solution (with and without the original `data.json` file), but unfortunately I'm still experiencing the same issue.

**Comment by fefumo** [comment]
I faced the same issue. Tried reinstalling twice and nothing helped. Then I tried ("just for fun")  to use original obsidian export option and, to my surprise, it also didn't work. So my solution to this problem was as funny as it may sound: i just deleted the plugin for the third time, rebooted -- and everything worked! Before installing the plugin again, I checked the original export function -- and it was back to normal. 

Even though i am not sure this comment will help anyone, but if it does - then it's served its purpose.

**Comment by l1xnan** [comment]
> @l1xnan I've tried your solution (with and without the original `data.json` file), but unfortunately I'm still experiencing the same issue.

Normally, even if there is a problem with the plugin, since there is no intrusion of any kind, it should not affect the official export.  What error is being reported in the developer console now?

**Comment by Seb-stian** [comment]
> @Seb-stian Normally, even if there is a problem with the plugin, since there is no intrusion of any kind, it should not affect the official export. What error is being reported in the developer console now? What version of Obsidian are you using now?

So apparently the plugin didn't work because I had a `Custom` page size (which is what I wanted). It works otherwise. Besides `electron is not defined` there are no errors in the developer console. My Obsidian is on version `1.7.7`.

**Comment by Latisha19** [comment]
> @Ethan-Crisp @its-truce @Latisha19 In fact, I've never been able to reproduce these issues.  I don't know what changes the new version of Obsidian has made, but it has indeed affected the plugin.  I made some modifications to the areas where I suspected problems might occur and released a new version.  If possible, could you guys help test it?  It would be best to back up and delete the plugin's `data.json` file before retesting. Thank you very much.

Thanks, I will try it tomorrow.
Hope it can work, too.

**Comment by l1xnan** [comment]
@Seb-stian The debug mode is designed to check whether there are any abnormalities in rendering. If the export fails, press `Ctrl + Shift + I` to open the developer console and check if there are any abnormal errors.

**Comment by Seb-stian** [comment]
@l1xnan
```
plugin:better-export-pdf:20225
Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Invalid pageSize Custom
    at t.ipcRendererInternal.invoke (node:electron/js2c/renderer_init:2:11128)
    at async exportToPDF (plugin:better-export-pdf:20213:16)
    at async handleExport (plugin:better-export-pdf:20801:11)
```

**Comment by Seb-stian** [comment]
Just from skim reading, is [this](https://github.com/l1xnan/obsidian-better-export-pdf/blob/18f553099ad85d1c93739b7fbc40765b2abf2fd6/src/pdf.ts#L376C3-L376C85) correct?
```ts
if (config["pageSize"] == "Custom" && config["pageWidth"] && config["pageHeight"])
```

Do I really have to set the page width and height for it to be calculated?

**Comment by l1xnan** [comment]
@Seb-stian I roughly understand the cause of the problem.  The issue is that when the page size is set to "Custom", the validation of the width/height is not carried out.  I will release a new version.  Thank you for your feedback.

**Comment by generic-user** [comment]
Thanks for looking into this. If helpful, I have my log data attached here: 
```log
PDF.js v4.9.0 (build: ?)
Message: Cannot set properties of undefined (setting 'onPull')
_otherError @ pdf.viewer.min.mjs:21
app.js:1 UnknownErrorException
(anonymous) @ app.js:1
node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at WebViewElement.getWebContentsId (node:electron/js2c/renderer_init:2:23196)
    at e.<computed> [as executeJavaScript] (node:electron/js2c/renderer_init:2:27416)
    at eval (plugin:better-export-pdf:20665:39)
    at Array.forEach (<anonymous>)
    at ExportConfigModal.calcWebviewSize (plugin:better-export-pdf:20663:19)
    at async ExportConfigModal.appendWebviews (plugin:better-export-pdf:20757:5)
    at async eval (plugin:better-export-pdf:20969:11)
node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at WebViewElement.getWebContentsId (node:electron/js2c/renderer_init:2:23196)
    at e.<computed> [as executeJavaScript] (node:electron/js2c/renderer_init:2:27416)
    at eval (plugin:better-export-pdf:20665:39)
    at Array.forEach (<anonymous>)
    at ExportConfigModal.calcWebviewSize (plugin:better-export-pdf:20663:19)
    at async ExportConfigModal.appendWebviews (plugin:better-export-pdf:20757:5)
    at async eval (plugin:better-export-pdf:20969:11)
node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at WebViewElement.getWebContentsId (node:electron/js2c/renderer_init:2:23196)
    at e.<computed> [as executeJavaScript] (node:electron/js2c/renderer_init:2:27416)
    at eval (plugin:better-export-pdf:20665:39)
    at Array.forEach (<anonymous>)
    at ExportConfigModal.calcWebviewSize (plugin:better-export-pdf:20663:19)
    at async ExportConfigModal.appendWebviews (plugin:better-export-pdf:20757:5)
    at async eval (plugin:better-export-pdf:20969:11)
plugin:better-export-pdf:20228 Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at WebViewElement.getWebContentsId (node:electron/js2c/renderer_init:2:23196)
    at e.<computed> [as printToPDF] (node:electron/js2c/renderer_init:2:27416)
    at exportToPDF (plugin:better-export-pdf:20216:24)
    at handleExport (plugin:better-export-pdf:20811:17)
exportToPDF @ plugin:better-export-pdf:20228
node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at WebViewElement.getWebContentsId (node:electron/js2c/renderer_init:2:23196)
    at e.<computed> [as executeJavaScript] (node:electron/js2c/renderer_init:2:27416)
    at eval (plugin:better-export-pdf:20665:39)
    at Array.forEach (<anonymous>)
    at ExportConfigModal.calcWebviewSize (plugin:better-export-pdf:20663:19)
    at async ExportConfigModal.appendWebviews (plugin:better-export-pdf:20757:5)
    at async eval (plugin:better-export-pdf:20969:11)

```

**Comment by l1xnan** [comment]
@generic-user I suspect that the note rendering issue might be caused by a plugin conflict.  Could you try disabling all other plugins except this one to test if the problem still persists?  Also, could you share your notes (after removing sensitive information)?  I need to reproduce the problem and debug the code.
Also, is your note very large? It's possible that large files could also cause this problem.

**Comment by Latisha19** [comment]
Yesterday, I also needed to set the page size to "Custom", so I tried to update from version 1.10.0 to version 1.10.2.
But it cannot make me fill any value into.

![Image](https://github.com/user-attachments/assets/ac35dd3d-aca7-481f-a0cf-795bf248547c)

Direct click "Export" got:

![Image](https://github.com/user-attachments/assets/c5581c02-5459-45ba-9a2d-8273b46783c3)

What else can I do?

Thanks for any reply.

**Comment by l1xnan** [comment]
If your `Page Size` is set to `Custom`, then you need to add the `Width/Height` configuration, and it cannot be left empty.

**Comment by Latisha19** [comment]
That is the bug made: it didn't allow me to fill any value.

**Comment by Somnia1337** [comment]
I also encountered this issue, but I *magically* found a **non-reproducible workaround** that allowed me to export the PDF I needed:

1. My console logs:
```
plugin:better-export-pdf:20288 Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Failed to generate PDF: Printing failed
    at IpcRendererInternal.invoke (node:electron/js2c/renderer_init:2:11410)
    at async exportToPDF (plugin:better-export-pdf:20276:16)
    at async handleExport (plugin:better-export-pdf:25375:11)
```
2. I opened the sandbox vault and installed the plugin, trying to reproduce the issue.
3. Export was a success in sandbox (**with "header" and "footer" turned on**).
4. I turned "header" and "footer" on (in my main vault) and successfully exported the PDF I wanted.
5. **After all that, no matter which vault, no matter the configs, the issue sticked around and no more successful exports**.

Maybe next time I run into the same problem, I’ll take a closer look into it.

**Comment by l1xnan** [comment]
@Somnia1337 

This kind of error is generally caused by the underlying `webview.printToPDF` function, rather than the plugin itself (the plugin calls this underlying interface). Such issues occur at intervals, and I haven't been able to figure out the cause. Since Electron no longer recommends using `webview`, I think the underlying part may lack maintenance and have bugs. The official export uses `webContents.printToPDF`, which has fewer problems. Unfortunately, the plugin doesn't have the permission to access this interface. In case of such a situation, restarting Obsidian or the computer can solve the problem. 
```
Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Failed to generate PDF: Printing failed
```

**Comment by Somnia1337** [comment]
Thanks so much for the detailed explanation — that really helps clarify what’s going on behind the scenes. I wasn’t aware that `webview.printToPDF` was deprecated, so that’s good to know.

Thanks again for the additional context!

**Comment by XbuLee** [comment]
I ran into this issue too. I used Gemini to help tweak `main.js` and came up with the following change, which seems to fix it on my end:



---------------
Okay,既然 `main.js` 没有被混淆，我们可以直接应用之前讨论的修改方案。

**核心修改逻辑回顾：**

1.  **`appendWebview`**：改造为返回一个 Promise，这个 Promise 只有在 webview 加载完成（`dom-ready`）并且内部的 CSS/JS 注入 *之后* 才 resolve。将 `this.webviews.push(preview)` 移动到 `dom-ready` 处理程序的末尾。
2.  **`appendWebviews`**：使用 `await Promise.all()` 等待所有改造后的 `appendWebview` 返回的 Promise 完成，确保所有 webview 都真正准备好了，再调用 `calcWebviewSize`。
3.  **`calcWebviewSize`**：移除 `sleep(500)`，并使用 `await Promise.all()` + `map` 来正确处理异步的 `executeJavaScript` 调用，增加错误处理。

**修改后的代码：**

请按以下步骤操作：

1.  **备份！** 再次强调，请先备份你的 `.obsidian/plugins/better-export-pdf/main.js` 文件。
2.  用文本编辑器打开 `main.js`。
3.  **找到 `appendWebview` 函数，并用以下代码替换它：**

    ```javascript
    async appendWebview(parentElement, doc) { // 修改了第一个参数名 e -> parentElement 更清晰
        // **修改开始：返回一个新的 Promise**
        return new Promise(async (resolve, reject) => { // 外层 Promise，内部也用了 async
            const webview = createWebview(this.scale); // 假设 createWebview 在别处定义并返回 webview 元素

            // **关键：添加 dom-ready 监听器**
            const handleDomReady = async () => {
                try {
                    console.log(`WebView DOM ready for: ${doc.title}`);
                    // this.completed = true; // 这个标记可能需要重新考虑其逻辑，或者在所有 webview 完成后设置

                    // --- CSS 插入 ---
                    const stylePromises = getAllStyles().map(css => webview.insertCSS(css).catch(err => console.warn(`Failed to insert style for ${doc.title}:`, err))); // 添加 catch
                    await Promise.all(stylePromises);

                    // --- CSS Snippet 插入 ---
                    if (this.config.cssSnippet && this.config.cssSnippet != "0") {
                        try {
                            const cssSnippet = await fs2.readFile(this.config.cssSnippet, { encoding: "utf8" });
                            const printCss = cssSnippet.replaceAll(/@media print\s*{([^}]+)}/g, "$1");
                            await webview.insertCSS(printCss).catch(err => console.warn(`Failed to insert printCss snippet for ${doc.title}:`, err));
                            await webview.insertCSS(cssSnippet).catch(err => console.warn(`Failed to insert cssSnippet for ${doc.title}:`, err));
                        } catch (error2) {
                            console.warn("Failed to read or insert CSS snippet:", error2);
                            // CSS snippet 失败通常不应该阻止导出
                        }
                    }

                    // --- JS 执行 ---
                    await webview.executeJavaScript(this.makeWebviewJs(doc)).catch(err => {
                        console.error(`Failed to execute initial JS for ${doc.title}:`, err);
                        throw err; // JS 执行失败可能影响内容，可以选择抛出错误
                    });
                    console.log(`Executed initial JS for: ${doc.title}`);


                    // --- Patch Style 插入 ---
                    const patchPromises = getPatchStyle().map(css => webview.insertCSS(css).catch(err => console.warn(`Failed to insert patch style for ${doc.title}:`, err)));
                    await Promise.all(patchPromises);

                    // **此时 webview 不仅 dom-ready，且初始内容已注入**
                    console.log(`WebView fully prepared for: ${doc.title}`);

                    // **重要：将准备好的 webview 添加到数组**
                    // 之前是在创建时添加，现在移到这里
                    // this.webviews.push(webview); // ***不要***在这里添加，因为 appendWebviews 会收集 resolve 的结果

                    // this.preview = webview; // 这个 preview 可能是最后一个的引用，如果需要所有 webview 的引用，应该在 appendWebviews 中收集

                    resolve(webview); // **Resolve Promise，表示此 webview 准备就绪**

                } catch (error) {
                    console.error(`Error during WebView preparation for ${doc.title}:`, error);
                    reject(error); // 如果 CSS/JS 注入失败，则 reject
                } finally {
                    // 清理监听器 (虽然 once: true 会自动清理，但显式移除更保险)
                    webview.removeEventListener('dom-ready', handleDomReady);
                    webview.removeEventListener('did-fail-load', handleFailLoad);
                }
            };

            // 加载失败处理
            const handleFailLoad = (event) => {
                console.error(`WebView failed to load for ${doc.title}:`, event.errorCode, event.errorDescription);
                // 清理监听器
                webview.removeEventListener('dom-ready', handleDomReady);
                webview.removeEventListener('did-fail-load', handleFailLoad);
                reject(new Error(`WebView for "${doc.title}" failed to load. Code: ${event.errorCode}`));
            };

            // 添加事件监听器
            webview.addEventListener('dom-ready', handleDomReady, { once: true });
            webview.addEventListener('did-fail-load', handleFailLoad, { once: true });

            // **将 webview 附加到父元素**
            // const preview = parentElement.appendChild(webview); // 原代码，preview 似乎没在函数外使用
            parentElement.appendChild(webview); // 直接附加

            // **不要** 在这里添加 webview 到 this.webviews 或 resolve Promise
        });
        // **修改结束**
    }
    ```

4.  **找到 `appendWebviews` 函数，并用以下代码替换它：**

    ```javascript
    async appendWebviews(el, render = true) {
        var _a3;
        el.empty();
        // **初始化 webviews 数组**
        this.webviews = []; // 确保每次调用都清空

        if (render) {
            this.svelte = mount(Progress, {
                target: el,
                props: {
                    // 动态设置 startCount/totalCount 可能更好
                    startCount: ((_a3 = this.docs) == null ? 0 : _a3.length) || 5 // 估算或等待获取
                }
            });
            const { data, docs } = await this.getAllFiles();
            this.docs = docs; // 确保设置了 this.docs

            // 更新 Svelte 组件的总数（如果支持）
            if (this.svelte && typeof this.svelte.set === 'function') {
                this.svelte.set({ totalCount: docs.length });
            }
            if (this.svelte && typeof this.svelte.initRenderStates === 'function') {
                 this.svelte.initRenderStates(data);
            }

            // 渲染文件（如果 renderFiles 返回 docs，则不需要此步骤）
             if (!(docs && docs.length > 0)) { // 假设 renderFiles 会填充 this.docs
                 await this.renderFiles(data, [], this.svelte.updateRenderStates); // 传递空数组，因为 renderFiles 会填充 this.docs
             } else {
                 await this.renderFiles(data, docs, this.svelte.updateRenderStates);
             }

        }

        el.empty(); // 清空进度条

        // **修改开始：等待所有 webview 完全准备好**
        try {
            console.log(`Starting to append ${this.docs ? this.docs.length : 0} webviews...`);
            // 使用 Promise.all 等待所有 appendWebview 返回的 Promise 完成
            // 这意味着所有的 webview 都已经 dom-ready 并且内部操作完成
            // 将准备好的 webview 收集到 this.webviews
            this.webviews = await Promise.all(
                (this.docs ?? []).map(async ({ doc }, i) => { // 使用 ?? [] 保证安全
                    const wrapperDiv = el.createDiv({ attr: { class: "webview-wrapper" } });
                    if (this.multiplePdf) {
                        wrapperDiv.createDiv({
                            text: `${i + 1}-${doc.title}`,
                            attr: { class: "filename", style:"margin-bottom: 5px; font-size: 0.8em; color: #ccc;" }
                        });
                    }
                    wrapperDiv.createDiv({ attr: { class: "print-size", style:"margin-bottom: 5px; font-size: 0.8em; color: #aaa;" } });

                    // 调用修改后的 appendWebview，它现在返回一个在准备好后 resolve 的 Promise
                    const readyWebview = await this.appendWebview(wrapperDiv, doc);
                    console.log(`Webview setup completed for ${doc.title}`);
                    return readyWebview; // 返回准备好的 webview
                })
            );

            // **现在可以安全地调用 calcWebviewSize**
            console.log("All webviews fully prepared. Calculating sizes...");
            if (this.webviews.length > 0) {
                 // 可能需要设置 this.preview 为第一个 webview，如果其他地方用到的话
                 this.preview = this.webviews[0];
                 await this.calcWebviewSize(); // 调用尺寸计算
                 this.togglePrintSize(); // 确保在计算完尺寸后切换可见性
            } else {
                console.warn("No webviews were successfully created.");
            }


        } catch (error) {
            // 处理 appendWebview 中可能发生的 reject
            console.error("Error during webview setup or preparation:", error);
            el.empty(); // 清空界面
            // 向用户显示更友好的错误信息
            const errorDiv = el.createDiv({ attr: { style: "color: red; padding: 10px; border: 1px solid red; border-radius: 5px;" } });
            errorDiv.createEl('strong', { text: "导出准备失败:" });
            errorDiv.createEl('p', { text: error.message || "未知错误，请检查笔记内容或网络连接。" });
            errorDiv.createEl('p', { text: "更多信息请查看开发者控制台 (Ctrl+Shift+I)。", style: "font-size: 0.9em; margin-top: 5px;" });
        }
        // **修改结束**
    }
    ```

5.  **找到 `calcWebviewSize` 函数，并用以下代码替换它（和上次回复类似）：**

    ```javascript
    async calcWebviewSize() {
        // await sleep(500); // **移除这个 sleep**

        if (!this.webviews || this.webviews.length === 0) {
            console.warn("calcWebviewSize called, but no webviews are ready.");
            return;
        }
        console.log(`Calculating size for ${this.webviews.length} webviews.`);

        // **修改开始：使用 Promise.all 处理所有尺寸计算**
        await Promise.all(this.webviews.map(async (webviewElement, i) => {
            try {
                // 添加超时逻辑
                const executionPromise = webviewElement.executeJavaScript("[document.body.offsetWidth, document.body.offsetHeight]");
                const timeoutPromise = new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout executing JS to get size')), 5000)); // 5秒超时

                const [width, height] = await Promise.race([executionPromise, timeoutPromise]);

                // **改进查找 sizeEl 的方式**
                const parentNode = webviewElement.closest('.webview-wrapper'); // 使用 closest 查找父级 wrapper
                const sizeEl = parentNode ? parentNode.querySelector(".print-size") : null; // 从 wrapper 查找

                if (sizeEl) {
                    // 使用 innerHTML 并用 <br> 换行，使用 &times; 作为乘号
                    sizeEl.innerHTML = `${width}&times;${height}px<br>${px2mm(width)}&times;${px2mm(height)}mm`;
                } else {
                    console.warn(`Size element not found for webview ${i}`);
                }
            } catch (error) {
                console.error(`Error calculating size for webview ${i} (${(this.docs && this.docs[i]) ? this.docs[i].doc.title : 'Unknown Doc'}):`, error);
                const parentNode = webviewElement.closest('.webview-wrapper');
                const sizeEl = parentNode ? parentNode.querySelector(".print-size") : null;
                if (sizeEl) {
                    sizeEl.innerHTML = `<span style="color: red;">尺寸计算失败: ${error.message}</span>`;
                }
                // 不再继续此 webview 的处理，但允许其他 webview 继续
            }
        }));
        console.log("Finished calculating all webview sizes.");
        // **修改结束**
    }
    ```

6.  **保存 `main.js` 文件。**
7.  **重启 Obsidian 或重载插件** （禁用再启用）。
8.  **测试导出功能。**

**重要变化解释：**

*   `appendWebview` 现在是一个真正的异步函数，它返回的 Promise 保证了 webview 的 `dom-ready` 事件已经触发，并且内部的 CSS/JS 注入尝试已经完成（或失败）。
*   `appendWebviews` 现在使用 `await Promise.all()` 来等待这些保证完成的 Promise。并且，它将成功准备好的 `webview` 元素收集到 `this.webviews` 数组中。
*   `calcWebviewSize` 不再需要 `sleep`，因为它现在操作的是保证已经准备好的 `webview` 元素数组。同时，它使用了 `Promise.all` 和 `map` 来正确等待所有 `executeJavaScript` 调用完成，并为每个调用添加了错误处理和超时。

这些修改应该能解决 `dom-ready` 的时序问题。如果还遇到其他问题，请提供新的错误日志。

> I seem to be getting these errors:
> 
> ```
> Uncaught (in promise) Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
>     at WebViewElement.getWebContentsId (node:electron/js2c/renderer_init:2:23741)
>     at e.<computed> [as executeJavaScript] (node:electron/js2c/renderer_init:2:27962)
>     at eval (plugin:better-export-pdf:20653:39)
>     at Array.forEach (<anonymous>)
>     at ExportConfigModal.calcWebviewSize (plugin:better-export-pdf:20651:19)
>     at async ExportConfigModal.appendWebviews (plugin:better-export-pdf:20745:5)
>     at async eval (plugin:better-export-pdf:20760:7)
> ```
> 
> ```
> plugin:better-export-pdf:20221 Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Failed to generate PDF: Printing failed
>     at t.ipcRendererInternal.invoke (node:electron/js2c/renderer_init:2:11899)
>     at async exportToPDF (plugin:better-export-pdf:20209:16)
>     at async handleExport (plugin:better-export-pdf:20793:11)
> ```
> 
> ```
> plugin:better-export-pdf:20156 Uncaught (in promise) TypeError: Cannot destructure property 'doc' of 'undefined' as it is undefined.
>     at exportToPDF (plugin:better-export-pdf:20156:53)
>     at handleExport (plugin:better-export-pdf:20793:17)
> ```
> 
> Tried reinstalling twice. I click Export, choose the location and click OK. Nothing happens.

**Comment by Latisha19** [comment]
> I haven't reproduced this issue. Could you please try deleting the data.json file in the plugin path and restarting Obsidian to see if it can return to normal?

I haven't done this until next time, I should use this feature.
Then I got it normally, don't know why...

Anyway, may I request a feature so that if I choose "Custom," the width and weight are filled automatically?
That means "Custom" will find now paper's width and weight, so it can fill them automatically.
